export { default as CollectionView } from './CollectionView'
export { default as ProductView } from './ProductView'
export { default as ArchivesView } from './ArchivesView'
export { default as PrivacyPolicyView } from './PrivacyPolicyView'
export { default as ShippingReturnsView } from './ShippingReturnsView'
